---
title: "Analise_exploratoria"
output: html_document
---
Temos casos sem a indicação do sexo do paciente, tornando as analises por sexo inconclusivas.
Cada linha representa um caso de covid.
Todos os casos foram notificados em 2025.

Dimensões do dataset

linhas: 318735   
Colunas: 35

>skim(data_set_analisado)

── Data Summary ────────────────────────
                           Values            
Name                       data_set_analisado
Number of rows             318735            
Number of columns          35                
_______________________                      
Column type frequency:                       
  character                5                 
  numeric                  30                
________________________                     
Group variables            None              

── Variable type: character ───────────────────────────────────────────────────────────────────────────
  skim_variable n_missing complete_rate min max empty n_unique whitespace
1 DT_NOTIFIC            0         1      10  10     0      347          0
2 UF                  101         1.000   2   2     0       27          0
3 MUNICIPIO             0         1       3  29     0     1682          0
4 PAIS                  0         1       4  20     0       16          0
5 SEXO                  0         1       1   1     0        3          0

── Variable type: numeric ─────────────────────────────────────────────────────────────────────────────
   skim_variable n_missing complete_rate     mean      sd       p0     p25     p50     p75    p100
 1 NU_NOTIFIC            0             1 3.18e+13 7.13e+9  3.17e13 3.17e13 3.18e13 3.18e13 3.18e13
 2 IDADE                 0             1 2.98e+ 1 3.24e+1 -1   e 0 3   e 0 9   e 0 6.3 e 1 1.41e 2
 3 FEBRE                 0             1 6.15e- 1 4.87e-1  0       0       1   e 0 1   e 0 1   e 0
 4 TOSSE                 0             1 8.04e- 1 3.97e-1  0       1   e 0 1   e 0 1   e 0 1   e 0
 5 GARGANTA              0             1 1.11e- 1 3.14e-1  0       0       0       0       1   e 0
 6 RESPIRATORIO          0             1 6.89e- 1 4.63e-1  0       0       1   e 0 1   e 0 1   e 0
 7 SATURACAO             0             1 5.37e- 1 4.99e-1  0       0       1   e 0 1   e 0 1   e 0
 8 DIARREIA              0             1 7.89e- 2 2.70e-1  0       0       0       0       1   e 0
 9 VOMITO                0             1 1.16e- 1 3.20e-1  0       0       0       0       1   e 0
10 FATOR_RISC            0             1 4.19e- 1 4.93e-1  0       0       0       1   e 0 1   e 0
11 CARDIOPATICO          0             1 1.49e- 1 3.56e-1  0       0       0       0       1   e 0
12 HEMATOLOGICO          0             1 8.97e- 3 9.43e-2  0       0       0       0       1   e 0
13 DOWN                  0             1 7.37e- 3 8.55e-2  0       0       0       0       1   e 0
14 HEPATICA              0             1 5.22e- 3 7.21e-2  0       0       0       0       1   e 0
15 ASMA                  0             1 6.91e- 2 2.54e-1  0       0       0       0       1   e 0
16 DIABETES              0             1 9.25e- 2 2.90e-1  0       0       0       0       1   e 0
17 NEUROLOGICO           0             1 4.26e- 2 2.02e-1  0       0       0       0       1   e 0
18 PNEUMOPATICO          0             1 5.20e- 2 2.22e-1  0       0       0       0       1   e 0
19 IMUNODEPRE            0             1 2.40e- 2 1.53e-1  0       0       0       0       1   e 0
20 RENAL                 0             1 2.32e- 2 1.50e-1  0       0       0       0       1   e 0
21 OBESIDADE             0             1 2.16e- 2 1.45e-1  0       0       0       0       1   e 0
22 DOR_ABD               0             1 5.54e- 2 2.29e-1  0       0       0       0       1   e 0
23 FADIGA                0             1 1.79e- 1 3.83e-1  0       0       0       0       1   e 0
24 PERD_OLFT             0             1 1.26e- 2 1.12e-1  0       0       0       0       1   e 0
25 PERD_PALA             0             1 1.31e- 2 1.14e-1  0       0       0       0       1   e 0
26 VACINA                0             1 2.61e- 1 4.39e-1  0       0       0       1   e 0 1   e 0
27 UTI                   0             1 2.60e- 1 4.39e-1  0       0       0       1   e 0 1   e 0
28 RAIOX_RES             0             1 1.43e- 1 3.50e-1  0       0       0       0       1   e 0
29 TOMO_RES              0             1 1.46e- 2 1.20e-1  0       0       0       0       1   e 0
30 AMOSTRA               0             1 9.23e- 1 2.67e-1  0       1   e 0 1   e 0 1   e 0 1   e 0

=== Total por sexo ===
SEXO  frequencia
  <chr>      <int>
1 F         154.193
2 I             44
3 M         164.498

=== Tabela de vacinação (coluna VACINA) ===

Vacinados e não vacinados
  vac_status        n  perc
  <chr>         <int> <dbl>
1 Não vacinado 235.426 0.739
2 Vacinado      83.309 0.261


=== Top 5 comorbidades por sexo ===

SEXO  comorbidade    n_sim
   <chr> <chr>        <int>
 1 F     CARDIOPATICO 26480
 2 F     DIABETES     16963
 3 F     ASMA         11832
 4 F     PNEUMOPATICO  8846
 5 F     NEUROLOGICO   6615
 6 I     ASMA             2
 7 I     CARDIOPATICO     1
 8 I     IMUNODEPRE       1
 9 I     NEUROLOGICO      1
10 I     OBESIDADE        1
11 M     CARDIOPATICO 21125
12 M     DIABETES     12531
13 M     ASMA         10189
14 M     PNEUMOPATICO  7736
15 M     NEUROLOGICO   6949

=== Top 5 sintoma por sexo ===

SEXO  sintoma       n_sim total_sexo   perc
   <chr> <chr>         <int>      <int>  <dbl>
 1 F     TOSSE        123517     495371 0.249 
 2 F     RESPIRATORIO 104813     495371 0.212 
 3 F     FEBRE         92314     495371 0.186 
 4 F     SATURACAO     83503     495371 0.169 
 5 F     FADIGA        28674     495371 0.0579
 6 I     TOSSE            36        139 0.259 
 7 I     RESPIRATORIO     34        139 0.245 
 8 I     FEBRE            29        139 0.209 
 9 I     SATURACAO        21        139 0.151 
10 I     GARGANTA          6        139 0.0432
11 M     TOSSE        132843     528052 0.252 
12 M     RESPIRATORIO 114611     528052 0.217 
13 M     FEBRE        103773     528052 0.197 
14 M     SATURACAO     87539     528052 0.166 
15 M     FADIGA        28399     528052 0.0538

=== Total de casos por faixa etária ===

faixa_etaria total_casos
   <fct>              <int>
 1 0-1                42944
 2 2-5                76814
 3 6-10               48724
 4 11-17              14297
 5 18-29               9786
 6 30-39               9241
 7 40-49              11688
 8 50-59              15381
 9 60-69              24081
10 70-79              29387
11 80+                34531

=== Total geral de casos por faixa etária e status vacinal ===

faixa_etaria status_vacinal total_casos
   <fct>        <fct>                <int>
 1 0-1          Não vacinado         31.707
 2 0-1          Vacinado             11.237
 3 2-5          Não vacinado         63.456
 4 2-5          Vacinado             13.358
 5 6-10         Não vacinado         37.081
 6 6-10         Vacinado             11.643
 7 11-17        Não vacinado         11.093
 8 11-17        Vacinado              3.204
 9 18-29        Não vacinado          7.927
10 18-29        Vacinado              1.859
11 30-39        Não vacinado          7.440
12 30-39        Vacinado              1.801
13 40-49        Não vacinado          9.484
14 40-49        Vacinado              2.204
15 50-59        Não vacinado         11.942
16 50-59        Vacinado              3.439
17 60-69        Não vacinado         16.108
18 60-69        Vacinado              7.973
19 70-79        Não vacinado         17.904
20 70-79        Vacinado             11.483
21 80+          Não vacinado         20.030
22 80+          Vacinado             14.501


Total de casos: 318735 
Casos em UTI: 83005 
Percentual em UTI: 26.04 %

=== Frequencia UTI por faica etaria ===
faixa_etaria n_uti perc_uti
   <fct>        <int>    <dbl>
 1 2-5          18212 21.9    
 2 0-1          11351 13.7    
 3 6-10         10833 13.1    
 4 70-79         8701 10.5    
 5 80+           8654 10.4    
 6 60-69         7513  9.05   
 7 50-59         4801  5.78   
 8 11-17         3894  4.69   
 9 40-49         3656  4.40   
10 18-29         2715  3.27   
11 30-39         2674  3.22   
12 NA               1  0.00120


=== Taxa de UTI (gravidade) por status vacinal ===
vac_status   n_casos n_uti taxa_uti
  <chr>       <int> <int>    <dbl>
Não vacinado  235.426 63107    0.268
Vacinado       83.309 19898    0.239


=== Tabela de casos UTI por faixa etária NÃO VACINADOS ===

   faixa_etaria n_casos_n_vac
   <fct>                <int>
 1 2-5                  15665
 2 0-1                   9014
 3 6-10                  8439
 4 70-79                 5349
 5 80+                   5208
 6 60-69                 5145
 7 50-59                 3796
 8 11-17                 3057
 9 40-49                 2970
10 18-29                 2267
11 30-39                 2196
12 NA                       1

=== Tabela de casos UTI por faixa etária VACINADOS ===

   faixa_etaria n_casos_vac
   <fct>              <int>
 1 80+                 3446
 2 70-79               3352
 3 2-5                 2547
 4 6-10                2394
 5 60-69               2368
 6 0-1                 2337
 7 50-59               1005
 8 11-17                837
 9 40-49                686
10 30-39                478
11 18-29                448

=== Tabela numero total de exames ===

  categoria   total percentual
  <chr>       <int>      <dbl>
1 Raio-X      45674      14.3 
2 Tomografia   4642       1.46
3 Sem exame  268419      84.2 
4 Total      318735     100   
